alfworld-vision:
  env_name: alfworld
  env_config:
    render_mode: vision
    alf_config_path: "${env:ALFWORLD_DATA}/alf-config.yaml"
    max_actions_per_step: 1
  train_size: 8
  test_size: 4

# navigation:
#   env_name: navigation
#   env_config:
#     render_mode: vision
#   train_size: 8
#   test_size: 4