# Dataset Generation Configuration for Benchmark

# ALFWorld with text mode
alfworld-text:
  env_name: alfworld
  env_config:
    render_mode: text
    alf_config_path: "${env:ALFWORLD_DATA}/alf-config.yaml"
    max_actions_per_step: 1
  train_size: 128  # Generate 128 training examples
  test_size: 32    # Generate 32 test examples

# ALFWorld with vision mode
# alfworld-vision:
#   env_name: alfworld
#   env_config:
#     render_mode: vision
#     alf_config_path: "${env:ALFWORLD_DATA}/alf-config.yaml"
#     max_actions_per_step: 1
#   train_size: 128
#   test_size: 32

# frozenlake:
#   env_name: frozenlake
#   env_config:
#     is_slippery: false
#     size: 4
#     render_mode: text
#   train_size: 128
#   test_size: 32