models:
  qwen_0.5b:
    provider: vllm
    model_name: Qwen/Qwen2.5-0.5B-Instruct
    max_tokens: 1024
    temperature: 0.7
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.9

  # qwen_vl_3b:
  #   provider: vllm
  #   model_name: Qwen/Qwen2.5-VL-3B-Instruct
  #   max_tokens: 1024
  #   temperature: 0.7
  #   tensor_parallel_size: 2
  #   gpu_memory_utilization: 0.9