seed: 42
train_path: "./data/sokoban-text-1-step/train.parquet"
test_path: "./data/sokoban-text-1-step/test.parquet"
"env1": {
  "env_name": "sokoban",
  'env_config': {
      'num_boxes': 1
  },
  "train_size": 1000,
  "test_size": 100,
}