seed: 42
train_path: "./data/sokoban-vision-6-step/train.parquet"
test_path: "./data/sokoban-vision-6-step/test.parquet"
"env1": {
  "env_name": "sokoban",
  'env_config': {
      'num_boxes': 1,
      'dim_room' : [6,6],
      'max_steps': 100,
      'render_mode': "vision",
      'min_actions_to_succeed': 5,
      'max_actions_per_step': 3
  },
  "train_size": 10000,
  "test_size": 1000,
}